version: "3.9"
name: dev-env-jvm-tuner
services:
  postgres-server:
    image: postgres:15.5
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - pg-jvm-tuner-data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  pg-jvm-tuner-data:
  grafana-data: